version: "2.4"
services:
    example_service:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PASSWD=${PASSWD}
        ports:
            - '2222:22'
        restart: always